version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - PGUSER=user
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/lib/postgresql/data
    container_name: psgrs_db-2

  app:
    image: airfix982/testapp:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      - "ConnectionStrings:Postgre=Host=psgrs_db-2;User Id=user;Database=postgres;Password=user;Port=5432;Pooling=false"
    restart: unless-stopped
    container_name: calculator-2

  nginx:
    container_name: nginx-lab-2
    hostname: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./TestClient/dist:/etc/dist
    ports:
      - "81:80"
      - "444:443"
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
